import {
  LOG_DEBUG_LABEL,
  LOG_ERROR_LABEL,
  LOG_FATAL_LABEL,
  LOG_INFO_LABEL,
  LOG_TRACE_LABEL,
  LOG_WARN_LABEL,
} from '../constants/log.constant';

export enum LogEnum {
  FATAL_LOG = `${LOG_FATAL_LABEL}`,
  ERROR_LOG = `${LOG_ERROR_LABEL}`,
  WARN_LOG = `${LOG_WARN_LABEL}`,
  INFO_LOG = `${LOG_INFO_LABEL}`,
  DEBUG_LOG = `${LOG_DEBUG_LABEL}`,
  TRACE_LOG = `${LOG_TRACE_LABEL}`,
}
